### ISSUE TITLE
RSpecによるテスト開発

### ISSUE THREAD

**Issue by br-to** [br-to/game-share#27]
1.rspecを使用するためのセットアップ
2.モデルのテスト実装
3.コントローラのテスト実装
4.ビューのテスト実装

**Comment by br-to** [comment]
<h2>ユーザー登録</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: 登録成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 登録失敗のflashメッセージが表示されれば失敗

<h2>ログイン</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: ログイン成功のflashメッセージが表示される、profile_pathに飛びuser.nameとuser.emailが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it ログイン失敗のflashメッセージが表示されれば失敗

<h2>ログアウト</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: ログアウト成功のflashメッセージが表示され、root_pathに移動すれば成功

<p>2. 異常系</p>
なし

<h2>プロフィールの編集</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: 編集成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 編集失敗のflashメッセージが表示されれば失敗

<h2>プロフィールの削除</h2>
<p>1. 正常系<p>
ii. it: 削除成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
なし

<h2>ゲームタイトルの登録</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: ゲームタイトル登録成功のflashメッセージが表示される、ゲーム一覧ページにゲームタイトルが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 登録失敗のflashメッセージが表示されれば失敗

<h2>ゲームタイトルの編集</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: 編集成功のflashメッセージが表示される、ゲーム詳細ページで編集したゲームタイトルが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 編集失敗のflashメッセージが表示されれば失敗

<h2>ゲームタイトルの削除</h2>
<p>1. 正常系<p>
i. it: 削除成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
なし

<h2>ゲームタイトル一覧の表示</h2>
<p>1. 正常系<p>
i. it: ゲームタイトルが作成順に表示されれば成功

<p>2. 異常系</p>
なし

<h2>感想・レビューの登録</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: 登録成功のflashメッセージが表示される、ゲーム詳細ページにレビューが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 登録失敗のflashメッセージが表示されれば失敗

<h2>感想・レビューの編集</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: 編集成功のflashメッセージが表示される、レビュー詳細ページにレビューが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it: 編集失敗のflashメッセージが表示されれば失敗

<h2>感想・レビューの削除</h2>
<p>1. 正常系<p>
i. it: 削除成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
なし

<h2>ネタバレレビューの登録</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される、ネタバレを含むにチェックを入れる
ii. it: 登録成功のflashメッセージが表示される、ネタバレページにネタバレレビューが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 登録失敗のflashメッセージが表示されれば失敗

<h2>ネタバレレビューの編集</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される、ネタバレを含むにチェックを入れる
ii. it: 編集成功のflashメッセージが表示される、ネタバレページにネタバレレビューが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 編集失敗のflashメッセージが表示されれば失敗

<h2>ネタバレレビューの削除</h2>
<p>1. 正常系<p>
i. it: 削除成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
なし

<h2>ナイスする</h2>
<p>1. 正常系<p>
i. it: ナイスをクリックすると、ナイスを取り消すが表示され、ナイス数のカウントが1増えれば成功

<p>2. 異常系</p>
なし

<h2>ナイスを取り消す</h2>
<p>1. 正常系<p>
i. it:ナイスを取り消すをクリックすると、ナイスが表示され、ナイス数のカウントが1減れば成功

<p>2. 異常系</p>
なし

<h2>コメントを登録</h2>
<p>1. 正常系<p>
i. context: 正しい値が入力される
ii. it: 登録成功のflashメッセージが表示される、レビュー詳細ページにコメントが表示されれば成功

<p>2. 異常系</p>
i. context: 不正な値が入力される
ii. it 登録失敗のflashメッセージが表示されれば失敗

<h2>コメントの削除</h2>
<p>1. 正常系<p>
i. it: 削除成功のflashメッセージが表示されれば成功

<p>2. 異常系</p>
なし

**Comment by toyokappa** [comment]
contextは条件を書くので、「~の場合」と書くのが普通かな。書き直さなくていいけど、specに書く場合はそれで書いてもらえると。ではこちらをもとにsystem specを作成してください。

**Comment by br-to** [comment]
> ## ユーザー登録
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: 登録成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 登録失敗のflashメッセージが表示されれば失敗
> 
> ## ログイン
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: ログイン成功のflashメッセージが表示される、profile_pathに飛びuser.nameとuser.emailが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it ログイン失敗のflashメッセージが表示されれば失敗
> 
> ## ログアウト
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: ログアウト成功のflashメッセージが表示され、root_pathに移動すれば成功
> 
> 2. 異常系
> 
> なし
> ## プロフィールの編集
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: 編集成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 編集失敗のflashメッセージが表示されれば失敗
> 
> ## プロフィールの削除
> 1. 正常系
> 
> ii. it: 削除成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> なし
> ## ゲームタイトルの登録
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: ゲームタイトル登録成功のflashメッセージが表示される、ゲーム一覧ページにゲームタイトルが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 登録失敗のflashメッセージが表示されれば失敗
> 
> ## ゲームタイトルの編集
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: 編集成功のflashメッセージが表示される、ゲーム詳細ページで編集したゲームタイトルが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 編集失敗のflashメッセージが表示されれば失敗
> 
> ## ゲームタイトルの削除
> 1. 正常系
> 
> i. it: 削除成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> なし
> ## ゲームタイトル一覧の表示
> 1. 正常系
> 
> i. it: ゲームタイトルが作成順に表示されれば成功
> 
> 2. 異常系
> 
> なし
> ## 感想・レビューの登録
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: 登録成功のflashメッセージが表示される、ゲーム詳細ページにレビューが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 登録失敗のflashメッセージが表示されれば失敗
> 
> ## 感想・レビューの編集
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: 編集成功のflashメッセージが表示される、レビュー詳細ページにレビューが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it: 編集失敗のflashメッセージが表示されれば失敗
> 
> ## 感想・レビューの削除
> 1. 正常系
> 
> i. it: 削除成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> なし
> ## ネタバレレビューの登録
> 1. 正常系
> 
> i. context: 正しい値が入力される、ネタバレを含むにチェックを入れる
> 
> ii. it: 登録成功のflashメッセージが表示される、ネタバレページにネタバレレビューが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 登録失敗のflashメッセージが表示されれば失敗
> 
> ## ネタバレレビューの編集
> 1. 正常系
> 
> i. context: 正しい値が入力される、ネタバレを含むにチェックを入れる
> 
> ii. it: 編集成功のflashメッセージが表示される、ネタバレページにネタバレレビューが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 編集失敗のflashメッセージが表示されれば失敗
> 
> ## ネタバレレビューの削除
> 1. 正常系
> 
> i. it: 削除成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> なし
> ## ナイスする
> 1. 正常系
> 
> i. it: ナイスをクリックすると、ナイスを取り消すが表示され、ナイス数のカウントが1増えれば成功
> 
> 2. 異常系
> 
> なし
> ## ナイスを取り消す
> 1. 正常系
> 
> i. it:ナイスを取り消すをクリックすると、ナイスが表示され、ナイス数のカウントが1減れば成功
> 
> 2. 異常系
> 
> なし
> ## コメントを登録
> 1. 正常系
> 
> i. context: 正しい値が入力される
> 
> ii. it: 登録成功のflashメッセージが表示される、レビュー詳細ページにコメントが表示されれば成功
> 
> 2. 異常系
> 
> i. context: 不正な値が入力される
> 
> ii. it 登録失敗のflashメッセージが表示されれば失敗
> 
> ## コメントの削除
> 1. 正常系
> 
> i. it: 削除成功のflashメッセージが表示されれば成功
> 
> 2. 異常系
> 
> なし
